#!/usr/bin/env python3
import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import target as target_mod


def generate_config(requested=None):
    root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    target_name, cfg = target_mod.resolve(root_dir, requested)

    project = cfg.get("project", {})
    memory = cfg.get("memory", {})
    switch_cfg = cfg.get("switch", {})
    wiiu_cfg = cfg.get("wiiu", {})
    cemu_cfg = cfg.get("cemu", {})

    proj_name = project.get("name", "WiiXLaunchMod")
    proj_version = project.get("version", "1.0.0")
    proj_author = project.get("author", "Developer")
    proj_desc = project.get("description", "WiiXLaunch Cross-Platform Mod")
    is_debug = project.get("debug", True)

    heap_size = memory.get("heap_size", "0x50000")
    jit_size = memory.get("jit_size", "0x10000")
    inline_pool_size = memory.get("inline_pool_size", "0x10000")
    log_buf_size = memory.get("log_buffer_size", 512)

    title_id = switch_cfg.get("title_id", "01007EF00011E000").lower()

    # Patch persistence control.
    patches_cfg = cfg.get("patches", {})
    patches_persist = bool(patches_cfg.get("persist", False))

    # Switch host module load point (exl_main vs fs_ready).
    load_point_names = {"exl_main": 0, "fs_ready": 1}
    load_point = switch_cfg.get("load_point", "exl_main")
    if load_point not in load_point_names:
        sys.stderr.write(
            "[ConfigGen] switch.load_point is %r; known values are %s\n"
            % (load_point, ", ".join(sorted(load_point_names))))
        sys.exit(1)
    load_point_id = load_point_names[load_point]

    gen_dir = os.path.join(root_dir, "build", "generated")
    gen_inc_dir = os.path.join(gen_dir, "include", "program")
    gen_switch_dir = os.path.join(gen_dir, "switch")
    os.makedirs(gen_inc_dir, exist_ok=True)
    os.makedirs(gen_switch_dir, exist_ok=True)

    debug_def = "#define EXL_DEBUG" if is_debug else ""
    # Drop-in configuration for exlaunch source/program/setting.hpp.
    setting_hpp_content = f"""#pragma once

#include "common.hpp"

#define EXL_MODULE_NAME "{proj_name}"
{debug_def}
#define EXL_USE_FAKEHEAP

namespace WiiXLaunch::Setting {{
    constexpr size_t HeapSize       = {heap_size};
    constexpr size_t JitSize        = {jit_size};
    constexpr size_t InlinePoolSize = {inline_pool_size};
    constexpr size_t LogBufferSize  = {log_buf_size};
}}

namespace exl::setting {{
    constexpr size_t HeapSize       = {heap_size};
    constexpr size_t JitSize        = {jit_size};
    constexpr size_t InlinePoolSize = {inline_pool_size};
    constexpr size_t LogBufferSize  = {log_buf_size};

    /* exlaunch's own sanity checks, on our numbers. */
    static_assert(ALIGN_UP(JitSize, PAGE_SIZE) == JitSize, "");
    static_assert(ALIGN_UP(InlinePoolSize, PAGE_SIZE) == InlinePoolSize, "");
}}
"""
    setting_hpp_path = os.path.join(gen_inc_dir, "setting.hpp")
    with open(setting_hpp_path, "w", encoding="utf-8") as f:
        f.write(setting_hpp_content)
    print(f"[ConfigGen] Generated {setting_hpp_path}")

    # Game identity fingerprinting settings.
    ident = cfg.get("identity", {}) or {}

    def _num(v, default=0):
        if v is None:
            return default
        if isinstance(v, str):
            return int(v, 0)
        return int(v)

    id_sw = ident.get("switch", {}) or {}
    id_wu = ident.get("wiiu", {}) or {}
    sw_off = _num(id_sw.get("offset"))
    sw_len = _num(id_sw.get("length"))
    wu_addr = _num(id_wu.get("address"))
    wu_len = _num(id_wu.get("length"))

    def _known(platform):
        # Null-terminated known build fingerprint list.
        rows = []
        for e in ident.get("known", []) or []:
            if (e.get("platform") or "").lower() != platform:
                continue
            rows.append('        { 0x%08X, "%s" },'
                        % (_num(e.get("fingerprint")), e.get("name", "?")))
        rows.append("        { 0, nullptr },")
        return "\n".join(rows)

    known_sw = _known("switch")
    known_wu = _known("wiiu")

    host_hpp = f"""#pragma once

// GENERATED by scripts/generate_config.py from targets/{target_name}.json.
// Do not edit; edit the target.

#include <cstdint>

namespace WiiXLaunch::Host {{
    // Which target this host was built as. Logged at boot, so a subsdk9 on an
    // SD card can say what it is rather than being identified by its date.
    constexpr char TargetName[]  = "{target_name}";
    constexpr char ProjectName[] = "{proj_name}";

    // Uppercase, because that is how Atmosphere spells a title id on disk and
    // the Switch host builds an SD path out of this.
    constexpr char TitleId[]     = "{title_id.upper()}";

    // sd:/WiiXLaunch/mods/<TitleId>, which is where this host looks first. One
    // SD card holds every game's modules; a graphic pack and a Wii U content
    // directory are already scoped to their title, and an SD card is not.
    constexpr char ModsDir[]     = "WiiXLaunch/mods/{title_id.upper()}";

    // 0 = exl_main, before the game's main.
    // 1 = the first file the game opens, for an SDK whose filesystem is not
    //     usable that early. See the target's //load_point note.
    constexpr int SwitchLoadPoint = {load_point_id};
    constexpr char SwitchLoadPointName[] = "{load_point}";

    // false: declared patches are verified and then RESTORED between LoadAll and
    // RunPhase, so the sample patch mod demonstrates its three outcomes without
    // outliving its own boot.
    // true: they stay, which is what a patch mod is for.
    constexpr bool PatchesPersist = {str(patches_persist).lower()};

    // --- which build of the game is this? --------------------------------
    //
    // The slice the host CRCs to fingerprint the running game, and the builds
    // this target has been told the answer for. Length 0 means this target
    // declares no identity, which the host reports rather than guessing past.
    // See include/wiixlaunch/game_version.hpp.
    constexpr uint32_t IdentitySwitchOffset = 0x{sw_off:08X};
    constexpr uint32_t IdentitySwitchLength = {sw_len};
    constexpr uint32_t IdentityWiiuAddress  = 0x{wu_addr:08X};
    constexpr uint32_t IdentityWiiuLength   = {wu_len};

    struct KnownBuild {{ uint32_t fingerprint; const char* name; }};

    // Terminated by a null name. Enrol a build by pasting the fingerprint the
    // host logs into the target's identity.known.
    constexpr KnownBuild KnownSwitchBuilds[] = {{
{known_sw}
    }};
    constexpr KnownBuild KnownWiiuBuilds[] = {{
{known_wu}
    }};
}}
"""
    host_path = os.path.join(root_dir, "include", "wiixlaunch", "generated_host.hpp")
    with open(host_path, "w", encoding="utf-8") as f:
        f.write(host_hpp)
    print(f"[ConfigGen] Generated {host_path}")

    wiixl_setting_path = os.path.join(root_dir, "include", "wiixlaunch", "generated_setting.hpp")
    with open(wiixl_setting_path, "w", encoding="utf-8") as f:
        f.write(setting_hpp_content)

    npdm_json = {
        "name": proj_name,
        "title_id": f"0x{title_id}",
        "title_id_range_min": switch_cfg.get("title_id_range_min", "0x0100000000010000"),
        "title_id_range_max": switch_cfg.get("title_id_range_max", "0x01ffffffffffffff"),
        "main_thread_stack_size": switch_cfg.get("main_thread_stack_size", "0x00100000"),
        "main_thread_priority": switch_cfg.get("main_thread_priority", 44),
        "default_cpu_id": switch_cfg.get("default_cpu_id", 0),
        "process_category": 0,
        "is_retail": True,
        "pool_partition": 0,
        "is_64_bit": True,
        "address_space_type": 3,
        "filesystem_access": {
            "permissions": "0xffffffffffffffff"
        },
        "service_access": switch_cfg.get("service_access", [
            "acc:u0", "aoc:u", "apm", "appletOE", "audin:u", "audout:u", "audren:u",
            "bsd:u", "caps:u", "csrng", "friend:u", "fsp-srv", "hid", "lm", "nifm:u",
            "nvdrv", "pctl", "pl:u", "set", "sfdnsres", "ssl", "time:u", "vi:u"
        ]),
        "kernel_capabilities": [
            {
                "type": "kernel_flags",
                "value": {
                    "highest_thread_priority": 59,
                    "lowest_thread_priority": 28,
                    "lowest_cpu_id": 0,
                    "highest_cpu_id": 2
                }
            },
            {
                "type": "application_type",
                "value": 1
            }
        ]
    }

    if "system_resource_size" in switch_cfg:
        npdm_json["system_resource_size"] = switch_cfg["system_resource_size"]

    exl_json_path = os.path.join(gen_switch_dir, "config.json")
    with open(exl_json_path, "w", encoding="utf-8") as f:
        json.dump(npdm_json, f, indent=4)
    print(f"[ConfigGen] Generated {exl_json_path}")

    root_dir_unix = root_dir.replace('\\', '/')

    # Optional WiiXLaunch game module includes.
    module_includes, chosen, ignored = target_mod.module_includes(root_dir, cfg)
    if chosen:
        print("[ConfigGen] game module(s): %s" % ", ".join(chosen))
    else:
        print("[ConfigGen] no game module - base surfaces only")
    if ignored:
        print("[ConfigGen] present in vendor/ but NOT built for this target: %s"
              % ", ".join(ignored))

    module_flags = "".join(f' -I"{inc}"' for inc in module_includes)

    # WIIXL_EXTRA_DEFINES environment variable overrides.
    extra = os.environ.get("WIIXL_EXTRA_DEFINES", "").strip()
    if extra:
        print(f"[ConfigGen] WIIXL_EXTRA_DEFINES={extra}")
        extra = " " + extra

    config_mk_content = f"""LOAD_KIND := {switch_cfg.get("load_kind", "Module")}
PROGRAM_ID := {title_id}
NPDM_JSON := config.json
PYTHON := python3
MOUNT_PATH := {switch_cfg.get("mount_path", "/mnt/sdcard")}
C_FLAGS := -I"{root_dir_unix}/include" -I"{root_dir_unix}/build/generated/include"{module_flags}{extra}
CXX_FLAGS := -I"{root_dir_unix}/include" -I"{root_dir_unix}/build/generated/include"{module_flags}{extra}
"""
    exl_mk_path = os.path.join(gen_switch_dir, "config.mk")
    with open(exl_mk_path, "w", encoding="utf-8") as f:
        f.write(config_mk_content)
    print(f"[ConfigGen] Generated {exl_mk_path}")

    wiiu_title_ids = wiiu_cfg.get("target_title_ids", ["00050000101C9400", "00050000101C9500"])
    formatted_tids = ", ".join([f"0x{tid}ULL" for tid in wiiu_title_ids])

    wiiu_hpp_content = f"""#pragma once

#include <cstdint>

#define WUPS_PLUGIN_NAME_STR "{proj_name}"
#define WUPS_PLUGIN_AUTHOR_STR "{proj_author}"
#define WUPS_PLUGIN_VERSION_STR "{proj_version}"
#define WUPS_PLUGIN_DESCRIPTION_STR "{proj_desc}"

namespace WiiXLaunch::WiiUConfig {{
    constexpr uint64_t TargetTitleIds[] = {{ {formatted_tids} }};
    constexpr uint32_t TargetTitleIdsCount = sizeof(TargetTitleIds) / sizeof(TargetTitleIds[0]);
}}
"""
    wiiu_hpp_path = os.path.join(root_dir, "include", "wiixlaunch", "generated_wiiu_config.hpp")
    with open(wiiu_hpp_path, "w", encoding="utf-8") as f:
        f.write(wiiu_hpp_content)
    print(f"[ConfigGen] Generated {wiiu_hpp_path}")

    # Cemu entry hook configuration.
    entry_hook = cemu_cfg.get("entry_hook", "0x00000000")
    entry_instr = cemu_cfg.get("entry_hook_instruction", "0x00000000")
    entry_hook_val = int(str(entry_hook), 16)
    entry_instr_val = int(str(entry_instr), 16)
    entry_return = entry_hook_val + 4

    if entry_hook_val != 0 and entry_instr_val == 0:
        raise SystemExit(
            "[ConfigGen] cemu.entry_hook is set to 0x%08X but cemu.entry_hook_instruction "
            "is missing or zero.\n"
            "  The pack overwrites that instruction with a branch, so the bootstrap has to "
            "replay it; without the word it would execute a zero and fall through into the "
            "game mid-prologue.\n"
            "  Disassemble entry_hook and record the instruction word there." %
            entry_hook_val)

    cemu_hpp_content = f"""#pragma once

// GENERATED by scripts/generate_config.py from targets/{target_name}.json - do not edit.
//
// The Cemu entry hook, as macros the bootstrap's asm() block can stringify.
// These are the only game-specific values base's bootstrap needs; everything
// else about it is game-agnostic.

#define WIIXL_CEMU_ENTRY_HOOK        0x{entry_hook_val:08X}
#define WIIXL_CEMU_ENTRY_RETURN      0x{entry_return:08X}
#define WIIXL_CEMU_ENTRY_RETURN_HI   0x{(entry_return >> 16) & 0xFFFF:04X}
#define WIIXL_CEMU_ENTRY_RETURN_LO   0x{entry_return & 0xFFFF:04X}
#define WIIXL_CEMU_ENTRY_DISPLACED   0x{entry_instr_val:08X}
"""
    cemu_hpp_path = os.path.join(root_dir, "include", "wiixlaunch", "generated_cemu_config.hpp")
    with open(cemu_hpp_path, "w", encoding="utf-8") as f:
        f.write(cemu_hpp_content)
    print(f"[ConfigGen] Generated {cemu_hpp_path}")

    print("\n[ConfigGen] Single Central Config successfully synchronized without modifying vendor submodules!")

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--target", default=None,
                    help="host target name; targets/<name>.json")
    generate_config(ap.parse_args().target)
