#!/usr/bin/env python3
"""Extract WIIXL_LOG's formatter from debug_log.hpp for host testing.

WiiXLaunch's Cemu payload has no libc, so debug_log.hpp carries its own printf:
impl::AppendChar/AppendStr/AppendUInt/AppendInt/AppendFloat and FormatText.
Everything on every platform logs through it, and it cannot be exercised on a
console - so it is pulled out here, verbatim, and run on the host.

Verbatim matters. Copying the function into the test would test the copy: the
bug this harness was written for (width specifiers like %02X printing literally
and consuming no argument) lived in the real one for a long time precisely
because nothing ever ran it anywhere it could be observed.

Run via build.bat / build.sh, which call this first.
"""

import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
# format.hpp, not debug_log.hpp. The formatter moved into its own header so
# that a .wxlm could use it too - a module cannot include debug_log.hpp,
# which reaches for the ring buffer and OSReport. The extraction still
# happens rather than the test just #including the header, because the test
# must compile it with NO WiiXLaunch include path at all: that is what
# proves it is freestanding, which is the property a module depends on.
HEADER = os.path.normpath(os.path.join(HERE, "..", "..", "include", "wiixlaunch", "format.hpp"))


def main():
    if not os.path.exists(HEADER):
        sys.stderr.write("cannot find %s\n" % HEADER)
        return 1

    lines = io.open(HEADER, encoding="utf-8").read().replace("\r\n", "\n").split("\n")

    try:
        start = next(i for i, l in enumerate(lines) if l.startswith("namespace impl {"))
        fmt = next(i for i, l in enumerate(lines) if l.startswith("inline uint32_t FormatText"))
        close = next(i for i in range(fmt + 1, len(lines)) if lines[i] == "}")
    except StopIteration:
        sys.stderr.write(
            "could not locate 'namespace impl {' .. FormatText in format.hpp.\n"
            "If that header was restructured, update the markers here.\n")
        return 1

    body = "\n".join(lines[start:close + 1])

    # THE EXTRACTION ITSELF HAS TO BE CHECKED. The markers are line-prefix
    # matches, so a restructure can make this slice a smaller region and still
    # "succeed" - producing a header that compiles and a test suite that
    # exercises less than it claims to. A too-short body, or one missing the
    # helpers FormatText dispatches to, means the markers no longer describe the
    # file. See the fourth rule in docs/framework/modules.md.
    required = ("FormatText", "AppendChar", "AppendStr", "AppendUInt",
                "AppendInt", "AppendFloat")
    missing = [n for n in required if n not in body]
    if missing:
        sys.stderr.write(
            "extracted %d lines from format.hpp but they do not contain: %s\n"
            "The 'namespace impl {' .. FormatText markers no longer describe the\n"
            "file. Update them here rather than shipping a partial extraction.\n"
            % (close - start + 1, ", ".join(missing)))
        return 1

    MIN_LINES = 60
    if (close - start + 1) < MIN_LINES:
        sys.stderr.write(
            "extracted only %d lines from debug_log.hpp, expected at least %d.\n"
            "That is too little to be the whole formatter; the markers have\n"
            "probably slipped.\n" % (close - start + 1, MIN_LINES))
        return 1

    out = (
        "// GENERATED by tools/format_test/extract.py - do not edit.\n"
        "// Extracted verbatim from include/wiixlaunch/debug_log.hpp.\n"
        "#pragma once\n"
        "#include <cstdint>\n"
        "#include <cstdarg>\n"
        "#include <cstddef>\n"
        "\n"
        "namespace WiiXLaunch { namespace Debug {\n"
        "\n"
        "constexpr uint32_t kMaxLogTextLen = 200;\n"
        "\n"
        + body +
        "\n\n} }  // namespace WiiXLaunch::Debug\n"
    )

    dst = os.path.join(HERE, "formatter_extract.hpp")
    io.open(dst, "w", encoding="utf-8").write(out)
    print("[format_test] extracted %d lines of format.hpp -> formatter_extract.hpp "
          "(%d required symbols present)" % (close - start + 1, len(required)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
