#pragma once

// GENERATED by scripts/generate_config.py from targets/botw.json - do not edit.
//
// The Cemu entry hook, as macros the bootstrap's asm() block can stringify.
// These are the only game-specific values base's bootstrap needs; everything
// else about it is game-agnostic.

#define WIIXL_CEMU_ENTRY_HOOK        0x03098928
#define WIIXL_CEMU_ENTRY_RETURN      0x0309892C
#define WIIXL_CEMU_ENTRY_RETURN_HI   0x0309
#define WIIXL_CEMU_ENTRY_RETURN_LO   0x892C
#define WIIXL_CEMU_ENTRY_DISPLACED   0x7C0802A6
