#pragma once

// GENERATED by scripts/generate_config.py from targets/botw.json.
// Do not edit; edit the target.

#include <cstdint>

namespace WiiXLaunch::Host {
    // Which target this host was built as. Logged at boot, so a subsdk9 on an
    // SD card can say what it is rather than being identified by its date.
    constexpr char TargetName[]  = "botw";
    constexpr char ProjectName[] = "WiiXLaunch_BotW";

    // Uppercase, because that is how Atmosphere spells a title id on disk and
    // the Switch host builds an SD path out of this.
    constexpr char TitleId[]     = "01007EF00011E000";

    // sd:/WiiXLaunch/mods/<TitleId>, which is where this host looks first. One
    // SD card holds every game's modules; a graphic pack and a Wii U content
    // directory are already scoped to their title, and an SD card is not.
    constexpr char ModsDir[]     = "WiiXLaunch/mods/01007EF00011E000";

    // 0 = exl_main, before the game's main.
    // 1 = the first file the game opens, for an SDK whose filesystem is not
    //     usable that early. See the target's //load_point note.
    constexpr int SwitchLoadPoint = 0;
    constexpr char SwitchLoadPointName[] = "exl_main";

    // false: declared patches are verified and then RESTORED between LoadAll and
    // RunPhase, so the sample patch mod demonstrates its three outcomes without
    // outliving its own boot.
    // true: they stay, which is what a patch mod is for.
    constexpr bool PatchesPersist = false;

    // --- which build of the game is this? --------------------------------
    //
    // The slice the host CRCs to fingerprint the running game, and the builds
    // this target has been told the answer for. Length 0 means this target
    // declares no identity, which the host reports rather than guessing past.
    // See include/wiixlaunch/game_version.hpp.
    constexpr uint32_t IdentitySwitchOffset = 0x00600000;
    constexpr uint32_t IdentitySwitchLength = 4096;
    constexpr uint32_t IdentityWiiuAddress  = 0x10200000;
    constexpr uint32_t IdentityWiiuLength   = 4096;

    struct KnownBuild { uint32_t fingerprint; const char* name; };

    // Terminated by a null name. Enrol a build by pasting the fingerprint the
    // host logs into the target's identity.known.
    constexpr KnownBuild KnownSwitchBuilds[] = {
        { 0xA982D2BC, "1.5.0" },
        { 0, nullptr },
    };
    constexpr KnownBuild KnownWiiuBuilds[] = {
        { 0xB8FC33E3, "v208" },
        { 0, nullptr },
    };
}
