"""Generated shrine chest registry. Do not edit by hand."""

# Source: check_inventory/shrine_chest_registry.csv
# current_sequential_id is intentionally not used as an AP runtime ID.

SHRINE_CHEST_REGISTRY = (
    {
        'name': "Akh Va'quot Shrine - Chest 1",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_450234134',
        'drop_actor': 'Item_Enemy_30',
        'hash_id_unsigned': 450234134,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Akh Va'quot Shrine - Chest 2",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2699775799',
        'drop_actor': 'Weapon_Spear_032',
        'hash_id_unsigned': 2699775799,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Akh Va'quot Shrine - Chest 3",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_4270154666',
        'drop_actor': 'Item_Ore_C',
        'hash_id_unsigned': 4270154666,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Bareeda Naag Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_159148495',
        'drop_actor': 'Weapon_Bow_016',
        'hash_id_unsigned': 159148495,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Bareeda Naag Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3513544036',
        'drop_actor': 'Item_Ore_A',
        'hash_id_unsigned': 3513544036,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Bosh Kala Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2677842568',
        'drop_actor': 'Item_Ore_F',
        'hash_id_unsigned': 2677842568,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Bosh Kala Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_4073483487',
        'drop_actor': 'Weapon_Lsword_002',
        'hash_id_unsigned': 4073483487,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Chaas Qeta Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2231710576',
        'drop_actor': 'Armor_014_Upper',
        'hash_id_unsigned': 2231710576,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Daag Chokah Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_3264264754',
        'drop_actor': 'Item_Enemy_30',
        'hash_id_unsigned': 3264264754,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Dagah Keek Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_849632171',
        'drop_actor': 'PutRupee_Silver',
        'hash_id_unsigned': 849632171,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Dah Hesho Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1908915428',
        'drop_actor': 'Item_Enemy_31',
        'hash_id_unsigned': 1908915428,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Dah Kaso Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_992999892',
        'drop_actor': 'Item_Enemy_30',
        'hash_id_unsigned': 992999892,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Daka Tuss Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1852894353',
        'drop_actor': 'Weapon_Lsword_027',
        'hash_id_unsigned': 1852894353,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Dako Tah Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1366576292',
        'drop_actor': 'PutRupee_Silver',
        'hash_id_unsigned': 1366576292,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Dako Tah Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2298702348',
        'drop_actor': 'Item_Enemy_30',
        'hash_id_unsigned': 2298702348,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Dako Tah Shrine - Chest 3',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2917484848',
        'drop_actor': 'Weapon_Shield_036',
        'hash_id_unsigned': 2917484848,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Dako Tah Shrine - Chest 4',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_4223476174',
        'drop_actor': 'Weapon_Sword_030',
        'hash_id_unsigned': 4223476174,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Daqa Koh Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3884443295',
        'drop_actor': 'PutRupee_Silver',
        'hash_id_unsigned': 3884443295,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Daqo Chisay Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_32387787',
        'drop_actor': 'Weapon_Sword_035',
        'hash_id_unsigned': 32387787,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Dila Maag Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3735012660',
        'drop_actor': 'Armor_048_Upper',
        'hash_id_unsigned': 3735012660,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Dow Na'eh Shrine - Chest 1",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_896824088',
        'drop_actor': 'Item_Ore_E',
        'hash_id_unsigned': 896824088,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Dow Na'eh Shrine - Chest 2",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_1114850190',
        'drop_actor': 'Weapon_Sword_027',
        'hash_id_unsigned': 1114850190,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Dow Na'eh Shrine - Chest 3",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_1961782765',
        'drop_actor': 'Item_Ore_F',
        'hash_id_unsigned': 1961782765,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Dunba Taag Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2319591679',
        'drop_actor': 'Weapon_Lsword_035',
        'hash_id_unsigned': 2319591679,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Dunba Taag Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3047743907',
        'drop_actor': 'Weapon_Bow_017',
        'hash_id_unsigned': 3047743907,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Etsu Korima Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_4075460597',
        'drop_actor': 'PutRupee_Gold',
        'hash_id_unsigned': 4075460597,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Gee Ha'rah Shrine - Chest",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2975470194',
        'drop_actor': 'Item_Ore_A',
        'hash_id_unsigned': 2975470194,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Goma Asaagh Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_289382806',
        'drop_actor': 'Weapon_Lsword_024',
        'hash_id_unsigned': 289382806,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Gorae Torr Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_1597604003',
        'drop_actor': 'Weapon_Lsword_034',
        'hash_id_unsigned': 1597604003,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Ha Dahamar Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_787648808',
        'drop_actor': 'PutRupee_Purple',
        'hash_id_unsigned': 787648808,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Hawa Koth Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_638977289',
        'drop_actor': 'Item_Ore_C',
        'hash_id_unsigned': 638977289,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Hawa Koth Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2441275272',
        'drop_actor': 'PutRupee_Gold',
        'hash_id_unsigned': 2441275272,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Hawa Koth Shrine - Chest 3',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_3284159718',
        'drop_actor': 'Item_Enemy_30',
        'hash_id_unsigned': 3284159718,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Hia Miu Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_262007905',
        'drop_actor': 'Item_Ore_C',
        'hash_id_unsigned': 262007905,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Hila Rao Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_771359327',
        'drop_actor': 'Item_Ore_E',
        'hash_id_unsigned': 771359327,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Hila Rao Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Wood_2545300147',
        'drop_actor': 'Obj_IceArrow_A_03',
        'hash_id_unsigned': 2545300147,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Ishto Soh Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_582159315',
        'drop_actor': 'Item_Ore_D',
        'hash_id_unsigned': 582159315,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Ishto Soh Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1505890884',
        'drop_actor': 'Item_Enemy_30',
        'hash_id_unsigned': 1505890884,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Ja Baij Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_235083489',
        'drop_actor': 'Weapon_Lsword_001',
        'hash_id_unsigned': 235083489,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Ja Baij Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_4192706961',
        'drop_actor': 'Item_Ore_F',
        'hash_id_unsigned': 4192706961,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Jee Noh Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_3852730446',
        'drop_actor': 'Item_Ore_E',
        'hash_id_unsigned': 3852730446,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Jitan Sa'mi Shrine - Chest",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_993230',
        'drop_actor': 'Weapon_Spear_034',
        'hash_id_unsigned': 993230,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Joloo Nah Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_296010651',
        'drop_actor': 'Weapon_Spear_029',
        'hash_id_unsigned': 296010651,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Joloo Nah Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2758576440',
        'drop_actor': 'Weapon_Lsword_029',
        'hash_id_unsigned': 2758576440,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Kaam Ya'tak Shrine - Chest 1",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_616546705',
        'drop_actor': 'Item_Enemy_30',
        'hash_id_unsigned': 616546705,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Kaam Ya'tak Shrine - Chest 2",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1402060224',
        'drop_actor': 'Weapon_Sword_003',
        'hash_id_unsigned': 1402060224,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Kaam Ya'tak Shrine - Chest 3",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2202095126',
        'drop_actor': 'Item_Ore_A',
        'hash_id_unsigned': 2202095126,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Kaam Ya'tak Shrine - Chest 4",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2914122144',
        'drop_actor': 'PutRupee_Silver',
        'hash_id_unsigned': 2914122144,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Kaam Ya'tak Shrine - Chest 5",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3497573834',
        'drop_actor': 'Weapon_Lsword_055',
        'hash_id_unsigned': 3497573834,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Kah Mael Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_215071769',
        'drop_actor': 'Item_Ore_A',
        'hash_id_unsigned': 215071769,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Kah Okeo Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_889586639',
        'drop_actor': 'PutRupee_Gold',
        'hash_id_unsigned': 889586639,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Kah Okeo Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2150412173',
        'drop_actor': 'KeySmall',
        'hash_id_unsigned': 2150412173,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Kah Okeo Shrine - Chest 3',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2402635144',
        'drop_actor': 'Weapon_Lsword_056',
        'hash_id_unsigned': 2402635144,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Kah Okeo Shrine - Chest 4',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3055684308',
        'drop_actor': 'Item_Enemy_31',
        'hash_id_unsigned': 3055684308,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Kah Okeo Shrine - Chest 5',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3147218512',
        'drop_actor': 'Weapon_Sword_025',
        'hash_id_unsigned': 3147218512,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Kah Okeo Shrine - Chest 6',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3495362814',
        'drop_actor': 'Weapon_Spear_035',
        'hash_id_unsigned': 3495362814,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Kah Yah Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_445242426',
        'drop_actor': 'Weapon_Lsword_003',
        'hash_id_unsigned': 445242426,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Kah Yah Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1223731997',
        'drop_actor': 'KeySmall',
        'hash_id_unsigned': 1223731997,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Kamia Omuna Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_2937439544',
        'drop_actor': 'Item_Ore_A',
        'hash_id_unsigned': 2937439544,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Kam Urog Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2374996813',
        'drop_actor': 'Weapon_Spear_002',
        'hash_id_unsigned': 2374996813,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Kam Urog Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3513966293',
        'drop_actor': 'Item_Ore_E',
        'hash_id_unsigned': 3513966293,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Ka'o Makagh Shrine - Chest 1",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_393155234',
        'drop_actor': 'Item_Ore_E',
        'hash_id_unsigned': 393155234,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Ka'o Makagh Shrine - Chest 2",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2042129072',
        'drop_actor': 'Weapon_Bow_001',
        'hash_id_unsigned': 2042129072,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Ka'o Makagh Shrine - Chest 3",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3705447709',
        'drop_actor': 'PutRupee_Gold',
        'hash_id_unsigned': 3705447709,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Katah Chuki Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_628803076',
        'drop_actor': 'Weapon_Spear_024',
        'hash_id_unsigned': 628803076,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Katosa Aug Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_130001776',
        'drop_actor': 'Weapon_Lsword_034',
        'hash_id_unsigned': 130001776,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Kaya Wan Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_4012296241',
        'drop_actor': 'Weapon_Sword_003',
        'hash_id_unsigned': 4012296241,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Kaya Wan Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Wood_4214849996',
        'drop_actor': 'Item_Enemy_30',
        'hash_id_unsigned': 4214849996,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Kay Noh Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_1396031621',
        'drop_actor': 'Weapon_Sword_029',
        'hash_id_unsigned': 1396031621,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Kay Noh Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3287407663',
        'drop_actor': 'KeySmall',
        'hash_id_unsigned': 3287407663,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Kayra Mah Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2928701109',
        'drop_actor': 'Item_Ore_B',
        'hash_id_unsigned': 2928701109,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Kayra Mah Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3410031031',
        'drop_actor': 'Obj_BombArrow_A_02',
        'hash_id_unsigned': 3410031031,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Kee Dafunia Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3263521738',
        'drop_actor': 'Weapon_Sword_034',
        'hash_id_unsigned': 3263521738,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Keeha Yoog Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2835421124',
        'drop_actor': 'Item_Ore_A',
        'hash_id_unsigned': 2835421124,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Keh Namut Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1490683918',
        'drop_actor': 'Weapon_Spear_001',
        'hash_id_unsigned': 1490683918,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Keive Tala Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1178751663',
        'drop_actor': 'Weapon_Shield_036',
        'hash_id_unsigned': 1178751663,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Kema Kosassa Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_4153981767',
        'drop_actor': 'PutRupee_Silver',
        'hash_id_unsigned': 4153981767,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Kema Zoos Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_987962398',
        'drop_actor': 'Weapon_Sword_030',
        'hash_id_unsigned': 987962398,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Ke'nai Shakah Shrine - Chest",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3073200707',
        'drop_actor': 'Item_Ore_C',
        'hash_id_unsigned': 3073200707,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Keo Ruug Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_944710900',
        'drop_actor': 'Weapon_Lsword_003',
        'hash_id_unsigned': 944710900,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Ketoh Wawai Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2936889658',
        'drop_actor': 'Item_Enemy_30',
        'hash_id_unsigned': 2936889658,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Kiah Toza Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1082925680',
        'drop_actor': 'Weapon_Bow_017',
        'hash_id_unsigned': 1082925680,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Kihiro Moh Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1235062787',
        'drop_actor': 'Weapon_Spear_035',
        'hash_id_unsigned': 1235062787,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Korgu Chideh Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_2953061699',
        'drop_actor': 'PutRupee_Gold',
        'hash_id_unsigned': 2953061699,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Korsh O'hu Shrine - Chest",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1956105793',
        'drop_actor': 'Weapon_Spear_033',
        'hash_id_unsigned': 1956105793,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Kuhn Sidajj Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_1547680732',
        'drop_actor': 'Item_Enemy_31',
        'hash_id_unsigned': 1547680732,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Kuh Takkar Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_294526304',
        'drop_actor': 'Weapon_Sword_034',
        'hash_id_unsigned': 294526304,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Lakna Rokee Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2561429726',
        'drop_actor': 'Weapon_Lsword_055',
        'hash_id_unsigned': 2561429726,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Lanno Kooh Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2852596923',
        'drop_actor': 'PutRupee_Gold',
        'hash_id_unsigned': 2852596923,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Maag Halan Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1178382884',
        'drop_actor': 'Item_Enemy_31',
        'hash_id_unsigned': 1178382884,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Maag No'rah Shrine - Chest",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_682054227',
        'drop_actor': 'PutRupee_Silver',
        'hash_id_unsigned': 682054227,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Mah Eliya Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_1344934344',
        'drop_actor': 'Weapon_Shield_022',
        'hash_id_unsigned': 1344934344,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Maka Rah Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_1297119120',
        'drop_actor': 'Item_Enemy_30',
        'hash_id_unsigned': 1297119120,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Maka Rah Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_2905879506',
        'drop_actor': 'Item_Ore_A',
        'hash_id_unsigned': 2905879506,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Maka Rah Shrine - Chest 3',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_4272783493',
        'drop_actor': 'Obj_BombArrow_A_03',
        'hash_id_unsigned': 4272783493,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Mezza Lo Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_114738522',
        'drop_actor': 'Weapon_Sword_035',
        'hash_id_unsigned': 114738522,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Mijah Rokee Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_246330360',
        'drop_actor': 'Weapon_Sword_034',
        'hash_id_unsigned': 246330360,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Mirro Shaz Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_309690636',
        'drop_actor': 'Weapon_Lsword_031',
        'hash_id_unsigned': 309690636,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Mirro Shaz Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1168499415',
        'drop_actor': 'Item_Enemy_31',
        'hash_id_unsigned': 1168499415,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Mirro Shaz Shrine - Chest 3',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2340212918',
        'drop_actor': 'Weapon_Lsword_031',
        'hash_id_unsigned': 2340212918,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Misae Suma Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3717856843',
        'drop_actor': 'Item_Ore_A',
        'hash_id_unsigned': 3717856843,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Mo'a Keet Shrine - Chest 1",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_418217937',
        'drop_actor': 'Item_Ore_B',
        'hash_id_unsigned': 418217937,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Mo'a Keet Shrine - Chest 2",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_4073019342',
        'drop_actor': 'Weapon_Sword_003',
        'hash_id_unsigned': 4073019342,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Mogg Latan Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_359699135',
        'drop_actor': 'PutRupee_Gold',
        'hash_id_unsigned': 359699135,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Mogg Latan Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_718693766',
        'drop_actor': 'Weapon_Spear_025',
        'hash_id_unsigned': 718693766,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Mogg Latan Shrine - Chest 3',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3819328534',
        'drop_actor': 'Weapon_Bow_013',
        'hash_id_unsigned': 3819328534,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Monya Toma Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2144851240',
        'drop_actor': 'Weapon_Sword_035',
        'hash_id_unsigned': 2144851240,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Mozo Shenno Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_56897618',
        'drop_actor': 'Item_Ore_A',
        'hash_id_unsigned': 56897618,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Muwo Jeem Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3517324741',
        'drop_actor': 'Weapon_Bow_035',
        'hash_id_unsigned': 3517324741,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Myahm Agana Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2175434126',
        'drop_actor': 'Weapon_Bow_029',
        'hash_id_unsigned': 2175434126,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Namika Ozz Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2855684808',
        'drop_actor': 'Weapon_Spear_034',
        'hash_id_unsigned': 2855684808,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Ne'ez Yohma Shrine - Chest",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_4248817833',
        'drop_actor': 'Weapon_Spear_027',
        'hash_id_unsigned': 4248817833,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Noe Rajee Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1095169988',
        'drop_actor': 'Weapon_Shield_041',
        'hash_id_unsigned': 1095169988,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Noya Neha Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_821435950',
        'drop_actor': 'Weapon_Shield_003',
        'hash_id_unsigned': 821435950,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Oman Au Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_3375369818',
        'drop_actor': 'Weapon_Bow_001',
        'hash_id_unsigned': 3375369818,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Owa Daim Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1182477274',
        'drop_actor': 'Weapon_Shield_035',
        'hash_id_unsigned': 1182477274,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Pumaag Nitae Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3450862395',
        'drop_actor': 'Weapon_Sword_051',
        'hash_id_unsigned': 3450862395,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Qaza Tokki Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2611637153',
        'drop_actor': 'Armor_048_Lower',
        'hash_id_unsigned': 2611637153,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Qua Raym Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2541023350',
        'drop_actor': 'Weapon_Lsword_003',
        'hash_id_unsigned': 2541023350,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Qua Raym Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Wood_3617692800',
        'drop_actor': 'KeySmall',
        'hash_id_unsigned': 3617692800,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Qukah Nata Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_731998508',
        'drop_actor': 'Armor_046_Lower',
        'hash_id_unsigned': 731998508,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Raqa Zunzo Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_3003260476',
        'drop_actor': 'Weapon_Shield_036',
        'hash_id_unsigned': 3003260476,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Ree Dahee Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1203109046',
        'drop_actor': 'Armor_014_Head',
        'hash_id_unsigned': 1203109046,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Rin Oyaa Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2081482182',
        'drop_actor': 'Item_Enemy_30',
        'hash_id_unsigned': 2081482182,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Rinu Honika Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_4057292846',
        'drop_actor': 'Weapon_Lsword_037',
        'hash_id_unsigned': 4057292846,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Ritaag Zumo Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_883436885',
        'drop_actor': 'Item_Enemy_31',
        'hash_id_unsigned': 883436885,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Rohta Chigah Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2785472328',
        'drop_actor': 'Weapon_Shield_023',
        'hash_id_unsigned': 2785472328,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Rok Uwog Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1203458803',
        'drop_actor': 'KeySmall',
        'hash_id_unsigned': 1203458803,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Rok Uwog Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_4120858762',
        'drop_actor': 'Weapon_Spear_031',
        'hash_id_unsigned': 4120858762,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Rona Kachta Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3962878289',
        'drop_actor': 'Weapon_Lsword_033',
        'hash_id_unsigned': 3962878289,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Rota Ooh Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_2001786182',
        'drop_actor': 'Weapon_Sword_031',
        'hash_id_unsigned': 2001786182,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Rota Ooh Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3566506040',
        'drop_actor': 'KeySmall',
        'hash_id_unsigned': 3566506040,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Rucco Maag Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_1708460808',
        'drop_actor': 'Item_Ore_E',
        'hash_id_unsigned': 1708460808,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Rucco Maag Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_2731610075',
        'drop_actor': 'Weapon_Bow_014',
        'hash_id_unsigned': 2731610075,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Ruvo Korbah Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2691561845',
        'drop_actor': 'KeySmall',
        'hash_id_unsigned': 2691561845,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Ruvo Korbah Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3155326400',
        'drop_actor': 'Obj_BombArrow_A_03',
        'hash_id_unsigned': 3155326400,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Ruvo Korbah Shrine - Chest 3',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3694474462',
        'drop_actor': 'Item_Enemy_31',
        'hash_id_unsigned': 3694474462,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Saas Ko'sah Shrine - Chest",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1249779666',
        'drop_actor': 'Weapon_Sword_033',
        'hash_id_unsigned': 1249779666,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Sah Dahaj Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_2489506180',
        'drop_actor': 'Weapon_Bow_035',
        'hash_id_unsigned': 2489506180,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Sasa Kai Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1835622564',
        'drop_actor': 'Weapon_Sword_034',
        'hash_id_unsigned': 1835622564,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Sato Koda Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1836215605',
        'drop_actor': 'Item_Enemy_31',
        'hash_id_unsigned': 1836215605,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Shada Naw Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_2733670140',
        'drop_actor': 'Weapon_Lsword_034',
        'hash_id_unsigned': 2733670140,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Shae Katha Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_50928817',
        'drop_actor': 'Weapon_Spear_035',
        'hash_id_unsigned': 50928817,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Shae Loya Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3612472744',
        'drop_actor': 'Item_Ore_D',
        'hash_id_unsigned': 3612472744,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Shae Loya Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_3658282587',
        'drop_actor': 'Weapon_Bow_017',
        'hash_id_unsigned': 3658282587,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Shae Mo'sah Shrine - Chest 1",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1306359972',
        'drop_actor': 'KeySmall',
        'hash_id_unsigned': 1306359972,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Shae Mo'sah Shrine - Chest 2",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1749408352',
        'drop_actor': 'Item_Ore_B',
        'hash_id_unsigned': 1749408352,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Shae Mo'sah Shrine - Chest 3",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2775322850',
        'drop_actor': 'Weapon_Lsword_037',
        'hash_id_unsigned': 2775322850,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Shae Mo'sah Shrine - Chest 4",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2783782463',
        'drop_actor': 'Obj_IceArrow_A_02',
        'hash_id_unsigned': 2783782463,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Sha Gehma Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_654507101',
        'drop_actor': 'KeySmall',
        'hash_id_unsigned': 654507101,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Sha Gehma Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2591211974',
        'drop_actor': 'Weapon_Sword_024',
        'hash_id_unsigned': 2591211974,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Shai Utoh Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_050_923248764',
        'drop_actor': 'Weapon_Sword_001',
        'hash_id_unsigned': 923248764,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Shai Utoh Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3173256521',
        'drop_actor': 'Item_Enemy_30',
        'hash_id_unsigned': 3173256521,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Shai Yota Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2006054206',
        'drop_actor': 'Weapon_Lsword_033',
        'hash_id_unsigned': 2006054206,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Sharo Lun Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_1630334883',
        'drop_actor': 'Weapon_Lsword_033',
        'hash_id_unsigned': 1630334883,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Sha Warvo Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_287351360',
        'drop_actor': 'Weapon_Bow_035',
        'hash_id_unsigned': 287351360,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Sha Warvo Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_699967431',
        'drop_actor': 'PutRupee_Purple',
        'hash_id_unsigned': 699967431,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Sheem Dagoze Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2966651740',
        'drop_actor': 'Weapon_Lsword_035',
        'hash_id_unsigned': 2966651740,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Shee Vaneer Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_4140941963',
        'drop_actor': 'Weapon_Lsword_041',
        'hash_id_unsigned': 4140941963,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Shee Venath Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1221975918',
        'drop_actor': 'Weapon_Spear_037',
        'hash_id_unsigned': 1221975918,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Sheh Rata Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1274382149',
        'drop_actor': 'Weapon_Lsword_051',
        'hash_id_unsigned': 1274382149,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Sheh Rata Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3463086557',
        'drop_actor': 'Item_Ore_E',
        'hash_id_unsigned': 3463086557,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Shira Gomar Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3187836279',
        'drop_actor': 'Obj_BombArrow_A_03',
        'hash_id_unsigned': 3187836279,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Sho Dantu Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_962037740',
        'drop_actor': 'PutRupee_Silver',
        'hash_id_unsigned': 962037740,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Shoda Sah Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Wood_3299660229',
        'drop_actor': 'Obj_IceArrow_A_03',
        'hash_id_unsigned': 3299660229,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Shoda Sah Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Wood_3647020470',
        'drop_actor': 'KeySmall',
        'hash_id_unsigned': 3647020470,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Shoqa Tatone Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_396797432',
        'drop_actor': 'Weapon_Sword_024',
        'hash_id_unsigned': 396797432,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Shora Hah Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_223462799',
        'drop_actor': 'PutRupee_Silver',
        'hash_id_unsigned': 223462799,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Shora Hah Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_304910307',
        'drop_actor': 'Weapon_Lsword_033',
        'hash_id_unsigned': 304910307,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Shora Hah Shrine - Chest 3',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1249330112',
        'drop_actor': 'Obj_IceArrow_A_02',
        'hash_id_unsigned': 1249330112,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Shora Hah Shrine - Chest 4',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3281368662',
        'drop_actor': 'Item_Enemy_31',
        'hash_id_unsigned': 3281368662,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Shora Hah Shrine - Chest 5',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3826616279',
        'drop_actor': 'Weapon_Sword_025',
        'hash_id_unsigned': 3826616279,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Shora Hah Shrine - Chest 6',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_4196993938',
        'drop_actor': 'Weapon_Bow_036',
        'hash_id_unsigned': 4196993938,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Soh Kofi Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3032109463',
        'drop_actor': 'Weapon_Bow_035',
        'hash_id_unsigned': 3032109463,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Suma Sahma Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_3298610380',
        'drop_actor': 'Weapon_Sword_030',
        'hash_id_unsigned': 3298610380,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Tah Muhl Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_79753044',
        'drop_actor': 'Weapon_Lsword_036',
        'hash_id_unsigned': 79753044,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Tah Muhl Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1015560256',
        'drop_actor': 'Item_Ore_B',
        'hash_id_unsigned': 1015560256,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Tah Muhl Shrine - Chest 3',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Wood_1061208573',
        'drop_actor': 'Item_Ore_E',
        'hash_id_unsigned': 1061208573,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Tah Muhl Shrine - Chest 4',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Wood_3853713592',
        'drop_actor': 'KeySmall',
        'hash_id_unsigned': 3853713592,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Tahno O'ah Shrine - Chest",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3913217232',
        'drop_actor': 'Armor_014_Lower',
        'hash_id_unsigned': 3913217232,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Takama Shiri Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2056438385',
        'drop_actor': 'Weapon_Bow_036',
        'hash_id_unsigned': 2056438385,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Ta'loh Naeg Shrine - Chest 1",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1648376382',
        'drop_actor': 'Weapon_Sword_041',
        'hash_id_unsigned': 1648376382,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Ta'loh Naeg Shrine - Chest 2",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2577142135',
        'drop_actor': 'Weapon_Shield_041',
        'hash_id_unsigned': 2577142135,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Ta'loh Naeg Shrine - Chest 3",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3163225088',
        'drop_actor': 'Item_Ore_E',
        'hash_id_unsigned': 3163225088,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Tawa Jinn Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_4013064750',
        'drop_actor': 'Weapon_Lsword_035',
        'hash_id_unsigned': 4013064750,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Tena Ko'sah Shrine - Chest",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3776874027',
        'drop_actor': 'Weapon_Spear_003',
        'hash_id_unsigned': 3776874027,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Tho Kayu Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_3348821939',
        'drop_actor': 'Weapon_Bow_015',
        'hash_id_unsigned': 3348821939,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Toh Yahsa Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_651697158',
        'drop_actor': 'Armor_046_Upper',
        'hash_id_unsigned': 651697158,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Toh Yahsa Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Wood_1608635741',
        'drop_actor': 'Item_Ore_E',
        'hash_id_unsigned': 1608635741,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'To Quomo Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1922807999',
        'drop_actor': 'Weapon_Lsword_024',
        'hash_id_unsigned': 1922807999,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Toto Sah Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1319070279',
        'drop_actor': 'KeySmall',
        'hash_id_unsigned': 1319070279,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Toto Sah Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1345302867',
        'drop_actor': 'Weapon_Shield_041',
        'hash_id_unsigned': 1345302867,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': "Tu Ka'loh Shrine - Chest",
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_832725204',
        'drop_actor': 'Armor_048_Head',
        'hash_id_unsigned': 832725204,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Tutsuwa Nima Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1101189494',
        'drop_actor': 'Weapon_Spear_033',
        'hash_id_unsigned': 1101189494,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Voo Lota Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2260374746',
        'drop_actor': 'Weapon_Sword_033',
        'hash_id_unsigned': 2260374746,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Voo Lota Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2875625519',
        'drop_actor': 'KeySmall',
        'hash_id_unsigned': 2875625519,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Wahgo Katta Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_322360761',
        'drop_actor': 'Item_Ore_F',
        'hash_id_unsigned': 322360761,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Yah Rin Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_1735097170',
        'drop_actor': 'Weapon_Sword_003',
        'hash_id_unsigned': 1735097170,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Yah Rin Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_4049467582',
        'drop_actor': 'Item_Ore_E',
        'hash_id_unsigned': 4049467582,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Ya Naga Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_319620032',
        'drop_actor': 'Weapon_Sword_041',
        'hash_id_unsigned': 319620032,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Yowaka Ita Shrine - Chest 1',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_777293012',
        'drop_actor': 'Weapon_Bow_029',
        'hash_id_unsigned': 777293012,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Yowaka Ita Shrine - Chest 2',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Iron_1562844085',
        'drop_actor': 'Obj_BombArrow_A_02',
        'hash_id_unsigned': 1562844085,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Zalta Wa Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_3918894197',
        'drop_actor': 'Weapon_Bow_035',
        'hash_id_unsigned': 3918894197,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Ze Kasho Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_2075859436',
        'drop_actor': 'Weapon_Spear_028',
        'hash_id_unsigned': 2075859436,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
    {
        'name': 'Zuna Kai Shrine - Chest',
        'persistent_flag': 'CDungeon_TBox_Dungeon_Stone_1161464155',
        'drop_actor': 'Weapon_Sword_033',
        'hash_id_unsigned': 1161464155,
        'assignment_status': 'provisional_assignment',
        'verified': False,
    },
)

SHRINE_CHEST_BY_NAME = {
    entry['name']: entry for entry in SHRINE_CHEST_REGISTRY
}
