#!/usr/bin/env python3
"""Converts an image into an unswizzled linear RGBA8 texture header for use
with WiiXLaunch's GX2 graphics injection API (GX2::CreateTexture).

Usage:
    python scripts/pack_texture_gx2.py <image> <output_name> [--out include/]
"""
import argparse
import pathlib
import sys
from PIL import Image


def main():
    parser = argparse.ArgumentParser(description="Pack image for GX2 texture injection")
    parser.add_argument("image", type=pathlib.Path, help="Input image file")
    parser.add_argument("name", type=str, help="C++ identifier base name")
    parser.add_argument("--out", type=pathlib.Path, default=pathlib.Path("include"), help="Output directory")
    args = parser.parse_args()

    if not args.image.exists():
        sys.exit(f"Error: image '{args.image}' does not exist")

    img = Image.open(args.image).convert("RGBA")
    width, height = img.size
    rgba_bytes = img.tobytes()

    args.out.mkdir(parents=True, exist_ok=True)
    header_path = args.out / f"{args.name.lower()}_texture_bytes_gx2.hpp"

    var_prefix = "".join(part.capitalize() for part in args.name.split("_"))

    lines = [
        "#pragma once",
        "#include <cstdint>",
        "#include <cstddef>",
        "",
        f"// Generated by scripts/pack_texture_gx2.py from {args.image.name} - do not edit.",
        f"constexpr int k{var_prefix}TextureWidth = {width};",
        f"constexpr int k{var_prefix}TextureHeight = {height};",
        f"constexpr size_t k{var_prefix}TextureSize = {len(rgba_bytes)};",
        "",
        f"alignas(256) inline const uint8_t g_{var_prefix}TextureBytes[] = {{",
    ]

    for i in range(0, len(rgba_bytes), 16):
        chunk = rgba_bytes[i:i+16]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hex_vals},")

    lines.append("};")
    lines.append("")

    header_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {header_path} ({width}x{height}, {len(rgba_bytes)} bytes)")


if __name__ == "__main__":
    main()
